export const CHECK_STAFF_PERMISSION = 'app/staff/CHECK_STAFF_PERMISSION'
export const CHECK_STAFF_PERMISSION_SUCCESS = 'app/staff/CHECK_STAFF_PERMISSION_SUCCESS'
export const CHECK_STAFF_PERMISSION_FAILURE = 'app/staff/CHECK_STAFF_PERMISSION_FAILURE'
