FROM casecommons/ca_intake_base_image:latest


ENV APP_HOME /ca_intake
RUN mkdir $APP_HOME
WORKDIR $APP_HOME
RUN mkdir /build_artefacts

ENV BUNDLE_PATH /ca_intake/ruby_gems

RUN gem install bundler
COPY Gemfile Gemfile.lock ./
COPY package.json ./

RUN bundle install -j24
RUN yarn

COPY scripts/build.sh /usr/local/bin/build.sh
RUN chmod +x /usr/local/bin/build.sh

COPY . ./

ENTRYPOINT ["build.sh"]
