inherit_from: .rubocop_todo.yml

Metrics/LineLength:
  Max: 100

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - 'ruby_gems/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'config/routes.rb'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/AbcSize:
  Exclude:
    - 'spec/**/*.rb'

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
