const COUNTIES = Object.freeze({
  alameda: 'Alameda',
  alpine: 'Alpine',
  amador: 'Amador',
  butte: 'Butte',
  calaveras: 'Calaveras',
  colusa: 'Colusa',
  contra_Costa: 'Contra Costa',
  del_norte: 'Del Norte',
  el_dorado: 'El Dorado',
  fresno: 'Fresno',
  glenn: 'Glenn',
  humboldt: 'Humboldt',
  imperial: 'Imperial',
  inyo: 'Inyo',
  kern: 'Kern',
  kings: 'Kings',
  lake: 'Lake',
  lassen: 'Lassen',
  los_angeles: 'Los Angeles',
  madera: 'Madera',
  marin: 'Marin',
  mariposa: 'Mariposa',
  mendocino: 'Mendocino',
  merced: 'Merced',
  modoc: 'Modoc',
  mono: 'Mono',
  monterey: 'Monterey',
  napa: 'Napa',
  nevada: 'Nevada',
  orange: 'Orange',
  placer: 'Placer',
  plumas: 'Plumas',
  riverside: 'Riverside',
  sacramento: 'Sacramento',
  san_benito: 'San Benito',
  san_bernardino: 'San Bernardino',
  san_diego: 'San Diego',
  san_francisco: 'San Francisco',
  san_joaquin: 'San Joaquin',
  san_luis_Obispo: 'San Luis Obispo',
  san_mateo: 'San Mateo',
  santa_barbara: 'Santa Barbara',
  santa_clara: 'Santa Clara',
  santa_cruz: 'Santa Cruz',
  shasta: 'Shasta',
  sierra: 'Sierra',
  siskiyou: 'Siskiyou',
  solano: 'Solano',
  sonoma: 'Sonoma',
  stanislaus: 'Stanislaus',
  state_of_california: 'State of California',
  sutter: 'Sutter',
  tehama: 'Tehama',
  trinity: 'Trinity',
  tulare: 'Tulare',
  tuolumne: 'Tuolumne',
  ventura: 'Ventura',
  yolo: 'Yolo',
  yuba: 'Yuba',
})

export default COUNTIES
