default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['PG_HOST'] ? ENV['PG_HOST'] : 'localhost' %>
  port: <%= ENV['PG_PORT'] ? ENV['PG_PORT'] : 5432 %>
  username: <%= ENV['PG_USER'] ? ENV['PG_USER'] : 'casebook' %>
  password: <%= ENV['PG_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] %>

development:
  <<: *default
  database: intake_accelerator_development

test:
  <<: *default
  database: intake_accelerator_test

production:
  <<: *default
  database: <%= ENV.fetch('DATABASE_NAME', 'intake_accelerator_production') %>
