# config/feature.yml
development:
  features:
    release_one: false
    release_two: false
    authentication: <%= ENV.fetch('AUTHENTICATION', false) %>
    centralized_sessions: true
    referral_submit: <%= ENV.fetch('REFERRAL_SUBMIT', false) %>

test:
  features:
    release_one: false
    release_two: false
    authentication: false
    centralized_sessions: true
    referral_submit: false

production:
  features:
    release_one: <%= ENV.fetch('RELEASE_ONE', false) %>
    release_two: <%= ENV.fetch('RELEASE_TWO', false) %>
    authentication: <%= ENV.fetch('AUTHENTICATION', false) %>
    centralized_sessions: <%= ENV.fetch('CENTRALIZED_SESSIONS', false) %>
    referral_submit: <%= ENV.fetch('REFERRAL_SUBMIT', false) %>
