# config/feature.yml
development:
  features:
    release_one: false
    authentication: false
    centralized_sessions: true
    people_search_tpt: false
    referral_submit: false

test:
  features:
    release_one: false
    authentication: false
    centralized_sessions: true
    people_search_tpt: false
    referral_submit: false

production:
  features:
    release_one: <%= ENV.fetch('RELEASE_ONE', false) %>
    authentication: <%= ENV.fetch('AUTHENTICATION', false) %>
    centralized_sessions: <%= ENV.fetch('CENTRALIZED_SESSIONS', false) %>
    people_search_tpt: <%= ENV.fetch('PEOPLE_SEARCH_TPT', false) %>
    referral_submit: <%= ENV.fetch('REFERRAL_SUBMIT', false) %>
