# config/feature.yml
development:
  features:
    authentication: <%= ENV.fetch('AUTHENTICATION', false) %>
    perry_version_two: true
    centralized_sessions: true
    hoi_from_intake_api: false
    investigations: true
    snapshot: true
    screenings: true

test:
  features:
    authentication: false
    perry_version_two: true
    centralized_sessions: true
    hoi_from_intake_api: false
    investigations: true
    snapshot: true
    screenings: true

production:
  features:
    authentication: <%= ENV.fetch('AUTHENTICATION', false) %>
    perry_version_two: <%= ENV.fetch('PERRY_VERSION_TWO', true) %>
    centralized_sessions: <%= ENV.fetch('CENTRALIZED_SESSIONS', false) %>
    hoi_from_intake_api: <%= ENV.fetch('HOI_FROM_INTAKE_API', false) %>
    investigations: <%= ENV.fetch('INVESTIGATIONS', true) %>
    snapshot: <%= ENV.fetch('SNAPSHOT', true) %>
    screenings: <%= ENV.fetch('SCREENINGS', true) %>
